name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Simulating Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: |
            build/
            !build/**/*.map
