name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Simulating Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: |
            build/
            !build/**/*.map

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Display structure of downloaded files
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform builds, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifact for Docker build
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./build

      - name: Display structure of Docker build context
        run: ls -R ./build

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: vitoriakotowski/devops-assigment:latest

    discord:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Run Discord Webhook
          uses: johnnyhuy/actions-discord-git-webhook@main
          with:
            webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
